---
- name: Install ntp
  become: true
  become_user: root
  community.general.pacman:
    name:
      - ntp

- name: Enable and start NTP synchronisation
  become: true
  become_user: root
  ansible.builtin.systemd:
    name: systemd-timesyncd.service
    enabled: true
    state: started

- name: Set timezone and hardware clock
  become: true
  become_user: root
  community.general.timezone:
    hwclock: '{{ ntp_hwclock }}'
    name: '{{ ntp_timezone }}'
