---
- name: Install go-jira
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.command: go install github.com/go-jira/jira/cmd/jira@latest
  changed_when: true

- name: Ensure directory exists
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.file:
    path: ~/.jira.d/
    state: directory
    mode: 0755

- name: Template go-jira config
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.template:
    src: config.yml
    dest: ~/.jira.d/config.yml
    mode: 0644

- name: Install dependencies for cookie scriptlet
  become: true
  become_user: root
  community.general.pacman:
    name:
      - sqlite3
      - jq

- name: Template get-jira-cookies-from-qutebrowser
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.template:
    src: get-jira-cookies-from-qutebrowser.sh
    dest: ~/.jira.d/get-jira-cookies-from-qutebrowser.sh
    mode: 0755
