---
- name: Install go-jira
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.command: go install github.com/go-jira/jira/cmd/jira@latest

- name: Ensure directory exists
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.file:
    path: ~/.jira.d/
    state: directory

- name: Template go-jira config
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.template:
    src: config.yml
    dest: ~/.jira.d/config.yml
