---
- name: Get rid of the service
  ansible.builtin.include_tasks:
    file: remove-service.yml
  loop:
    - suspend-i3lock@

- name: Check if wrapper file exists
  ansible.builtin.stat:
    path: /usr/local/bin/i3lock-arch-ansible
  register: wrapper_file

- name: Get rid of wrapper file
  become: true
  become_user: root
  ansible.builtin.file:
    path: /usr/local/bin/i3lock-arch-ansible
    state: absent
