---
- name: Get rid of i3 implementation
  ansible.builtin.include_tasks:
    file: i3-cleanup.yml

- name: Get rid of dpms implementation
  ansible.builtin.include_tasks:
    file: dpms-cleanup.yml

- name: Install swaylock
  become: true
  become_user: root
  community.general.pacman:
    name:
      - swaylock
      - swayidle

- name: Template sway plugin
  ansible.builtin.include_role:
    name: helper_sway_plugin
  vars:
    helper_sway_plugin_template_name: swaylock-plugin

- name: Template the wrapper file
  become: true
  become_user: root
  ansible.builtin.template:
    src: swaylock-arch-ansible
    dest: /usr/local/bin/swaylock-arch-ansible
    mode: 0755

- name: Properly bootstrap wallpaper
  when: vars.swaylock_wallpaper
  block:
    - name: Ensure directory exists
      ansible.builtin.file:
        path: ~/.config/swaylock/wallpapers
        state: directory
        mode: 0755

    # Commands that don't change the "important" state are marked as non-changeable
    - name: Create temporary directory
      ansible.builtin.tempfile:
        state: directory
        suffix: swaylock
      register: swaylock_tempdir
      changed_when: false

    - name: Copy the base wallpaper
      ansible.builtin.copy:
        src: wallpapers/{{ vars.swaylock_wallpaper }}
        dest: "{{ swaylock_tempdir.path }}/wallpaper"
        mode: 0644
      changed_when: false

    - name: Resize and remove metadata
      # Resize image and get rid of metadata
      # so the hashes are deterministic
      ansible.builtin.command:
        chdir: "{{ swaylock_tempdir.path }}"
        # The resize ! parameter allows changing ratio
        cmd: convert wallpaper -strip -resize "{{ vars.display_resolution }}!" wallpaper-resized
      changed_when: false

    - name: Remove metadata (exiftool)
      # For whatever reason imagemagick leaves png:tIME on some images
      # exiftool handles it properly
      ansible.builtin.command:
        chdir: "{{ swaylock_tempdir.path }}"
        cmd: exiftool -all= wallpaper-resized
      changed_when: false

    - name: Copy the modified wallpaper
      ansible.builtin.copy:
        src: "{{ swaylock_tempdir.path }}/wallpaper-resized"
        dest: ~/.config/swaylock/wallpapers/{{ vars.swaylock_wallpaper }}
        mode: 0644
