---
- name: Install i3status-rust
  become: true
  become_user: root
  pacman:
    name:
      - i3status-rust

- name: Install fonts (awesome)
  become: true
  become_user: root
  pacman:
    name:
      - ttf-font-awesome

- name: Ensure directory exists
  become: yes
  become_user: "{{ user.name }}"
  file:
    path: ~/.config/i3status-rust/
    state: directory
    recurse: yes

- name: Template status config
  become: yes
  become_user: "{{ user.name }}"
  template:
    src: config.toml
    dest: ~/.config/i3status-rust/config.toml
