---
- name: Template config
  become: true
  become_user: root
  ansible.builtin.template:
    src: 30-dpms.conf
    dest: /etc/X11/xorg.conf.d/30-dpms.conf
    mode: 0644

- name: Install caffeine-ng
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    state: present
    name:
      - caffeine-ng

- name: Copy suspend service file
  become: true
  become_user: root
  ansible.builtin.copy:
    src: suspend-dpms@.service
    dest: /etc/systemd/system/
    mode: 0644

- name: Enable suspend service file
  become: true
  become_user: root
  ansible.builtin.systemd:
    name: suspend-dpms@{{ user_name }}
    enabled: true

- name: Copy resume service file
  become: true
  become_user: root
  ansible.builtin.copy:
    src: resume-dpms@.service
    dest: /etc/systemd/system/
    mode: 0644

- name: Enable resume service file
  become: true
  become_user: root
  ansible.builtin.systemd:
    name: resume-dpms@{{ user_name }}
    enabled: true
