---
- name: Install fish
  become: true
  become_user: root
  community.general.pacman:
    name:
      - fish

- name: Ensure directory exists
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.file:
    path: ~/.config/fish
    state: directory
    mode: 0755

- name: Template fish config
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.template:
    src: config.fish
    dest: ~/.config/fish/
    mode: 0644

- name: Template fish plugins config
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.template:
    src: plugins.fish
    dest: ~/.config/fish/plugins.fish
    mode: 0644
  register: var_fish_plugins

- name: Ensure directory exists
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.file:
    path: ~/.config/fish/functions
    state: directory
    mode: 0755

- name: Copy fundle setup script
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.template:
    src: fundle.fish
    dest: ~/.config/fish/functions
    mode: 0600
  register: var_fundle_script

- name: Get plugins
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.shell: fish -c "fundle install" && fish -c "fundle update"
  when: var_fish_plugins.changed or var_fundle_script.changed
  changed_when: true

- name: Ensure scriptlets directory exists
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.file:
    path: ~/.config/fish/ansible/fish
    state: directory
    mode: 0755

- name: Template fish scriptlets
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.template:
    src: "{{ item }}"
    dest: ~/.config/fish/ansible/fish/
    mode: 0644
  loop:
    - blocks.fish
    - aws.fish

- name: Enable shell
  become: true
  become_user: root
  ansible.builtin.user:
    name: "{{ user_name }}"
    shell: '{{ user_shell | default("/bin/bash") }}'
    state: present
