---
- name: Install fish
  become: true
  become_user: root
  community.general.pacman:
    name:
      - fish

- name: Ensure directory exists
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.file:
    path: ~/.config/fish
    state: directory
    mode: 0755

- name: Template fish configs
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.template:
    src: "{{ item }}"
    dest: ~/.config/fish/
    mode: 0644
  loop:
    - config.fish
    - aws.fish
    - kubernetes.fish
    - blocks.fish
    - fish_variables

- name: Template fish plugins config
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.template:
    src: plugins.fish
    dest: ~/.config/fish/plugins.fish
    mode: 0644
  register: var_fish_plugins

- name: Ensure directory exists
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.file:
    path: ~/.config/fish/functions
    state: directory
    mode: 0755

- name: Copy fundle setup script
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.template:
    src: fundle.fish
    dest: ~/.config/fish/functions
    mode: 0644
  register: var_fundle_script

- name: Get plugins
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.shell: fish -c "fundle install" && fish -c "fundle update"
  when: var_fish_plugins.changed or var_fundle_script.changed
  changed_when: true

- name: Enable shell
  become: true
  become_user: root
  ansible.builtin.user:
    name: "{{ user.name }}"
    shell: '{{ user.shell | default("/bin/bash") }}'
    state: present
