---
- name: Install fish
  become: true
  become_user: root
  community.general.pacman:
    name:
      - fish

- name: Ensure directory exists
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.file:
    path: ~/.config/fish
    state: directory
    recurse: true

- name: Copy fish config
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.template:
    src: config.fish
    dest: ~/.config/fish/config.fish

# TODO: More generic approach for multiple config files
- name: Copy fish (plugins) config
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.template:
    src: plugins.fish
    dest: ~/.config/fish/plugins.fish
  register: var_fish_plugins

- name: Copy fish (AWS) config
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.template:
    src: aws.fish
    dest: ~/.config/fish/aws.fish

- name: Copy fish (kubernetes) config
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.template:
    src: kubernetes.fish
    dest: ~/.config/fish/kubernetes.fish

- name: Copy fish (blocks) config
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.template:
    src: blocks.fish
    dest: ~/.config/fish/blocks.fish

- name: Copy fish colors
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.template:
    src: fish_variables
    dest: ~/.config/fish/fish_variables

- name: Ensure directory exists
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.file:
    path: ~/.config/fish/functions
    state: directory
    recurse: true

- name: Copy fundle setup script
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.template:
    src: fundle.fish
    dest: ~/.config/fish/functions
  register: var_fundle_script

- name: Get plugins
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.shell: fish -c "fundle install" && fish -c "fundle update"
  when: var_fish_plugins.changed or var_fundle_script.changed
  changed_when: true

- name: Enable shell
  become: true
  become_user: root
  ansible.builtin.user:
    name: "{{ user.name }}"
    shell: '{{ user.shell | default("/bin/bash") }}'
    state: present
