#theme = "solarized-dark"
[theme]
theme = "modern"

[icons]
icons = "awesome6"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
format = " $icon $available "

[[block]]
block = "net"
device = "wlp3s0"
format = " $icon $speed_down "
interval = 5

#[[block]]
#block = "music"
#player = "spotify"
#buttons = ["play", "next"]

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "memory"
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95
format = " $icon $mem_avail "

[[block]]
block = "pacman"
interval = 600

[[block]]
block = "sound"

[[block]]
block = "temperature"
interval = 2
format = " $icon $max "

[[block]]
block = "custom"
command = "hostname"
interval = "once"

[[block]]
block = "battery"
interval = 10
format = " $icon $percentage {$time |} "
missing_format = ""

[[block]]
block = "time"
interval = 60
[block.format]
#full = " $icon $timestamp.datetime(f:'%a %Y-%m-%d %R %Z', l:fr_BE) "
full = " $icon $timestamp.datetime(f:'%a %d/%m %R', l:pl_PL) "
short = " $icon $timestamp.datetime(f:%R) "
