---
- name: Install vnstat
  become: true
  become_user: root
  pacman:
    name:
      - vnstat

- name: Set state of vnstat service
  become: true
  become_user: root
  systemd:
      name: vnstat
      state: "{{ vnstat_service_state }}"
      enabled: "{{ vnstat_enable_service | bool }}"
