---
x230:
  hosts:
    localhost:
      ansible_connection: local
  vars:
    ansible_python_interpreter: /usr/bin/python3
    i3_resolution: "1366x768"
    openssh_start_server: false
    openssh_enable_server: false
    i3_setup_g751_scripts: false
    i3_nopasswd_g751_scripts: false
    user:
      name: d0ku
      pub_name: dezeroku
      generate_ssh_key: true
      ssh_key_bits: 4096
      ssh_key_type: rsa
      shell: /bin/fish
      email: dezeroku@gmail.com
      gpg_key: 5D6772EEDDACD5B0
      always_git_gpg: true
    work:
      enabled: false
      jira_user: test@example.com
      jira_endpoint: jira.example.com
