---
local_machine:
  hosts:
    localhost:
      ansible_connection: local
  vars:
    ansible_python_interpreter: /usr/bin/python3

    # Don't run the updates by default
    pacman_update: false
    pacman_upgrade: false
    pacman_enable_multilib: false

    # Enable the local caching with pacoloco
    pacoloco_setup_server: false
    pacoloco_server_url: http://pacoloco-server:9129
    # This should be enabled if you have set up pacoloco server in your LAN
    # The server_host must match
    pacoloco_setup_client: false
    pacoloco_repo: archlinux-reflector

    openssh_start_server: false
    openssh_enable_server: false
    openssh_sshd_xforwarding: false

    # Set to false if you use kernel other than default `linux`
    # You'll also need to install the headers for the kernel
    virtualbox_modules_default_kernel: true

    display_resolution: 1920x1080

    sway_disable_touchpad: false
    sway_output_scale: 1
    yubikey_sway_autostart_otp: false

    setup_hardware_video_acceleration_enabled: true
    hardware_video_acceleration_providers: ["intel"]

    helper_fish_plugin_enabled: true

    firewall_enable_opensnitch: true

    user_name: dezeroku
    create_user_generate_ssh_key: true
    create_user_ssh_key_type: ed25519
    user_shell: /bin/fish
    user_email: dezeroku@gmail.com
    gpg_user_key: 6AC2332BCF8E1A97
    gpg_sign_git_commits: true

    # Override these if you want the push notifications support via pushover
    # otherwise just leave it as it is
    apprise_pushover_user_key: ""
    apprise_pushover_api_key: ""

    work_enabled: false
    work_jira_user: test@example.com
    work_jira_endpoint: jira.example.com

    bluetooth_enabled: false
    # TODO: set of variables defining if GUI is to be enabled
    # Settings this to true as default basically breaks the CLI only deployments
    helper_sway_plugin_enabled: true

    # TODO: change this to a more general flag
    bluetooth_install_gui: true
    networkmanager_install_gui: true
