---
- name: Core
  hosts: all
  become: true
  become_user: root
  roles:
    - {role: pacman, tags: ['pacman']}
    - {role: pacoloco, tags: ['pacoloco']}
    - {role: ntp, tags: ['ntp']}
    - {role: create_user, tags: ['create_user']}
    - {role: vconsole, tags: ['vconsole']}
    - {role: sudo, tags: ['sudo']}
    - {role: aur_builder, tags: ['aur_builder']}
    - {role: dns_cache, tags: ['dns_cache']}
    - {role: hardening, tags: ['hardening']}
    - {role: openssh, tags: ['openssh']}
  tags:
    - core

- name: Core (non-root)
  hosts: all
  roles:
    - {role: networkmanager, tags: ['networkmanager', 'desktop-utils']}
    - {role: firewall, tags: ['firewall', 'desktop-utils']}
  tags:
    - core
