#!/usr/bin/env bash
set -e

ansible-galaxy install -r requirements.yml

touch custom.yaml

ansible-playbook -i base.yaml -i custom.yaml site.yml --ask-become-pass --tags core,cli,desktop,desktop-tools,media,virtualization,social,browser,languages,editors,docker,utils,work,office,gaming,vpn
