#!/usr/bin/env bash
set -e

ansible-galaxy install -r requirements.yml
ansible-playbook -i base.yaml all.yml --tags core,cli,desktop,desktop-tools,media,virtualization,social,browser,languages,editors,docker,utils,work,office,gaming,vpn
