#!/usr/bin/env bash
set -e

ansible-galaxy install -r requirements.yml

touch custom.yml

# shellcheck disable=SC2046
ansible-playbook -i base.yaml -i custom.yml site.yml $( [[ "${CI_RUN_MODE}" != "true" ]] && printf %s '--ask-become-pass') --tags \
core,\
cli,\
desktop,\
desktop-tools,\
desktop-utils,\
media,\
virtualization,\
social,\
browser,\
languages,\
editors,\
docker,\
utils,\
work,\
office,\
gaming,\
vpn
