#!/usr/bin/env bash
set -e

ansible-galaxy install -r requirements.yml

touch custom.yml

ansible-playbook -i base.yaml -i custom.yml site.yml --ask-become-pass --tags \
core,\
cli,\
desktop,\
desktop-tools,\
desktop-utils,\
media,\
virtualization,\
social,\
browser,\
languages,\
editors,\
docker,\
utils,\
work,\
office,\
gaming,\
vpn
