---
- name: Core
  ansible.builtin.import_playbook: core.yml

- name: CLI
  ansible.builtin.import_playbook: cli.yml

- name: All
  hosts: all
  become: true
  become_user: "{{ user_name }}"
  roles:
    - {role: autorandr, tags: ['autorandr', 'desktop']}
    - {role: audio_control, tags: ['audio_control', 'desktop']}
    - {role: bluetooth, tags: ['bluetooth', 'desktop-utils', 'audio'], when: bluetooth_enabled}
    - {role: discord, tags: ['discord', 'social']}
    - {role: docker, tags: ['docker', 'docker']}
    - {role: dunst, tags: ['dunst', 'desktop']}
    - {role: dpms, tags: ['dpms', 'desktop']}
    - {role: exfat_utils, tags: ['exfat_utils', 'utils']}
    - {role: firefox, tags: ['firefox', 'browser']}
    - {role: flameshot, tags: ['flameshot', 'desktop']}
    - {role: fonts, tags: ['fonts', 'desktop']}
    - {role: fuse, tags: ['fuse', 'utils']}
    - {role: gimp, tags: ['gimp', 'desktop-utils']}
    - {role: go, tags: ['go', 'languages']}
    - {role: gparted, tags: ['gparted', 'desktop-utils']}
    - {role: i3lock, tags: ['i3lock', 'desktop']}
    - {role: i3status_rust, tags: ['i3status_rust', 'desktop']}
    - {role: imagemagick, tags: ['imagemagick', 'utils']}
    - {role: jira, tags: ['jira', 'work'], when: work_enabled}
    - {role: latex, tags: ['latex', 'office']}
    - {role: libreoffice, tags: ['libreoffice', 'office']}
    - {role: libvirt, tags: ['libvirt']}
    - {role: mesa, tags: ['mesa', 'desktop']}
    - {role: misc, tags: ['misc', 'utils']}
    - {role: mpv, tags: ['mpv', 'media']}
    - {role: networkmanager_applet, tags: ['networkmanager_applet', 'desktop']}
    - {role: npm, tags: ['npm', 'languages']}
    - {role: pcmanfm, tags: ['pcmanfm', 'desktop-utils']}
    - {role: powerline, tags: ['powerline', 'desktop']}
    - {role: pipewire, tags: ['pipewire', 'desktop', 'audio']}
    - {role: python3, tags: ['python3', 'languages']}
    - {role: qemu, tags: ['qemu', 'virtualization']}
    - {role: qutebrowser, tags: ['qutebrowser', 'browser']}
    - {role: redshift, tags: ['redshift', 'desktop']}
    - {role: rofi, tags: ['rofi', 'desktop']}
    - {role: rust, tags: ['rust', 'languages']}
    - {role: spotify, tags: ['spotify', 'media']}
    - {role: slack, tags: ['slack', 'work']}
    - {role: sxiv, tags: ['sxiv', 'desktop-utils']}
    - {role: udiskie, tags: ['udiskie', 'desktop']}
    - {role: vagrant, tags: ['vagrant', 'virtualization']}
    - {role: vim, tags: ['vim', 'editors']}
    - {role: vlc, tags: ['vlc', 'media']}
    - {role: vscode, tags: ['vscode', 'editors']}
    - {role: vnstat, tags: ['vnstat', 'utils']}
    - {role: wireguard_tools, tags: ['wireguard_tools', 'vpn']}
    - {role: xorg, tags: ['xorg', 'desktop']}
    - {role: yt_dlp, tags: ['yt_dlp', 'media']}
    - {role: yubikey, tags: ['yubikey', 'desktop-tools']}
    - {role: zathura, tags: ['zathura', 'desktop-tools']}
    - {role: hardware_video_acceleration, tags: ['hardware_video_acceleration', 'desktop'], when: setup_hardware_video_acceleration_enabled}
    - {role: zoom, tags: ['zoom', 'work']}
    # DEVELOPMENT
    - {role: sway, tags: ['sway', 'desktop']}
    - {role: wayland, tags: ['wayland', 'desktop']}
    - {role: foot, tags: ['foot', 'desktop']}
  tags:
    - install

- name: Unorganized
  ansible.builtin.import_playbook: unorganized.yml
