---
- name: Ensure directory exists
  become: true
  become_user: aur_builder
  ansible.builtin.file:
    path: "{{ dmarc_cat_build_dir }}"
    state: directory
    mode: 0755

- name: Copy files
  become: true
  become_user: aur_builder
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ dmarc_cat_build_dir }}"
    mode: 0644
  loop:
    - PKGBUILD

- name: Build and install
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    use: makepkg
    state: latest
    name:
      - dmarc-cat-dezeroku
    local_pkgbuild: "{{ dmarc_cat_build_dir }}"
