---
- name: Install xorg
  become: true
  become_user: root
  community.general.pacman:
    name:
      - xorg
      - xorg-xinit

- name: Ensure directory exists
  become: true
  become_user: root
  ansible.builtin.file:
    path: /etc/X11/xorg.conf.d
    state: directory
    mode: 0755

- name: Copy configs
  become: true
  become_user: root
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/X11/xorg.conf.d/
    mode: 0755
  loop:
    - 00-keyboard.conf
    - 30-touchpad.conf
