---
- name: Install qutebrowser
  become: true
  become_user: root
  community.general.pacman:
    name:
      - qutebrowser

- name: Ensure directory exists
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.file:
    path: ~/.config/qutebrowser
    state: directory
    mode: 0755

- name: Copy qutebrowser config
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.copy:
    src: qute_config.py
    dest: ~/.config/qutebrowser/config.py
    mode: 0644

- name: Ensure scripts directory exists
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.file:
    path: ~/.config/qutebrowser/scripts
    state: directory
    mode: 0755

- name: Copy video download script
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.copy:
    src: download_video.sh
    dest: ~/.config/qutebrowser/scripts/download_video.sh
    mode: 0755

- name: Ensure greasemonkey directory exists
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.file:
    path: ~/.config/qutebrowser/greasemonkey
    state: directory
    mode: 0755

- name: Copy youtube-adblock.user.js scriptlet
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.copy:
    src: youtube-adblock.user.js
    dest: ~/.config/qutebrowser/greasemonkey/youtube-adblock.user.js
    mode: 0755

- name: Install bitwarden CLI userscript dependency
  become: true
  become_user: root
  community.general.pacman:
    name:
      - python-tldextract

- name: Install brave adblocker to be used
  kewlfft.aur.aur:
    name:
      - python-adblock
    state: present
  become: true
  become_user: root

- name: Query default browser
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.command:
    cmd: xdg-settings get default-web-browser
  changed_when: false
  register: default_browser_check

- name: Set qutebrowser as the default browser
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.command:
    cmd: xdg-settings set default-web-browser org.qutebrowser.qutebrowser.desktop
  changed_when: true
  when: ("org.qutebrowser.qutebrowser.desktop" != default_browser_check.stdout)

- name: Install decoding for DRM sites (e.g. Netflix)
  kewlfft.aur.aur:
    name:
      - chromium-widevine
    state: present
  become: true
  become_user: aur_builder
  when: qutebrowser_install_widevine
