---
- name: Install qutebrowser
  become: true
  become_user: root
  pacman:
    name:
      - qutebrowser

- name: Ensure directory exists
  become: true
  become_user: "{{ user.name }}"
  file:
    path: ~/.config/qutebrowser
    state: directory
    recurse: yes

- name: Copy qutebrowser config
  become: true
  become_user: "{{ user.name }}"
  copy:
      src: qute_config.py
      dest: ~/.config/qutebrowser/config.py

- name: Ensure scripts directory exists
  become: true
  become_user: "{{ user.name }}"
  file:
    path: ~/.config/qutebrowser/scripts
    state: directory
    recurse: yes

- name: Copy download script
  become: true
  become_user: "{{ user.name }}"
  copy:
      src: download_video.sh
      dest: ~/.config/qutebrowser/scripts/download_video.sh

# TODO: move to separate bitwarden rol
- name: Install password manager and dependency
  become: true
  become_user: root
  pacman:
    name:
    - python-tldextract

- name: Install brave adblocker to be used
  aur:
    name:
      - python-adblock
    state: present
  become: true
  become_user: root

- name: Install decoding for DRM sites (e.g. Netflix)
  aur:
    name:
      - chromium-widevine
    state: present
  become: true
  become_user: aur_builder
  when: qutebrowser_install_widevine
