---
- name: Install qutebrowser
  become: true
  become_user: root
  community.general.pacman:
    name:
      - qutebrowser

- name: Ensure directory exists
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.file:
    path: ~/.config/qutebrowser
    state: directory
    mode: 0755

- name: Copy qutebrowser config
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.copy:
    src: qute_config.py
    dest: ~/.config/qutebrowser/config.py
    mode: 0644

- name: Ensure scripts directory exists
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.file:
    path: ~/.config/qutebrowser/scripts
    state: directory
    mode: 0755

- name: Copy download script
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.copy:
    src: download_video.sh
    dest: ~/.config/qutebrowser/scripts/download_video.sh
    mode: 0755

# TODO: move to separate bitwarden rol
- name: Install password manager and dependency
  become: true
  become_user: root
  community.general.pacman:
    name:
      - python-tldextract

- name: Install brave adblocker to be used
  kewlfft.aur.aur:
    name:
      - python-adblock
    state: present
  become: true
  become_user: root


# TODO: Can this be done with modifying ~/.config/mimeapps.list directly instead?
# It seems this would be cleaner
- name: Set qutebrowser as the default browser
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.command:
    cmd: xdg-settings set default-web-browser org.qutebrowser.qutebrowser.desktop
  changed_when: true

- name: Install decoding for DRM sites (e.g. Netflix)
  kewlfft.aur.aur:
    name:
      - chromium-widevine
    state: present
  become: true
  become_user: aur_builder
  when: qutebrowser_install_widevine
