---
- name: Install NetworkManager's applet
  become: true
  become_user: root
  community.general.pacman:
    name: network-manager-applet
    state: present

- name: Template sway plugin
  ansible.builtin.include_role:
    name: helper_sway_plugin
  vars:
    helper_sway_plugin_template_name: networkmanager-plugin
