---
- name: Install pulseaudio packages
  become: true
  become_user: root
  community.general.pacman:
    name:
      - alsa-utils
      - pulseaudio

- name: Install pulseaudio packages (Bluetooth)
  become: true
  become_user: root
  community.general.pacman:
    name:
      - pulseaudio-bluetooth
  when: pulseaudio_install_bluetooth

- name: Install pulseaudio bluetooth codecs from AUR
  kewlfft.aur.aur:
    name:
      - pulseaudio-modules-bt-git
    state: present
  become: true
  become_user: aur_builder

- name: Install pulseaudio equalizer plugin
  become: true
  become_user: root
  community.general.pacman:
    name:
      - pulseaudio-equalizer
  when: pulseaudio_install_equalizer

- name: Install pavucontrol
  become: true
  become_user: root
  community.general.pacman:
    name:
      - pavucontrol
  when: pulseaudio_install_pavucontrol

# TODO: add task that will bump sampler rate and in effect quality
