---
# mailctl-bin SEGFAULTs for me locally,
# installing the static binary from Github works
- name: Install mailctl
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    state: present
    name:
      - mailctl-bin

# This probably belongs more in the isync config
# But we won't really need it anywhere outside the mailctl context
- name: Install XOAUTH2 SASL helper
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    state: present
    name:
      - cyrus-sasl-xoauth

- name: Ensure config directory exists
  ansible.builtin.file:
    path: ~/.config/mailctl
    state: directory
    mode: 0755

- name: Template config files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: ~/.config/mailctl/{{ item }}
    mode: 0600
  loop:
    - config.yaml
    - services.yaml
