---
- name: Install i3status-rust
  become: true
  become_user: root
  community.general.pacman:
    name:
      - i3status-rust

- name: Install fonts (awesome)
  become: true
  become_user: root
  community.general.pacman:
    name:
      - ttf-font-awesome

- name: Ensure directory exists
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.file:
    path: ~/.config/i3status-rust/
    state: directory
    mode: 0755

- name: Template status config
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.template:
    src: config.toml
    dest: ~/.config/i3status-rust/config.toml
    mode: 0644
