---
- name: Install i3status-rust and inetutils (for hostname)
  become: true
  become_user: root
  community.general.pacman:
    name:
      - i3status-rust
      - inetutils

- name: Install fonts (awesome)
  become: true
  become_user: root
  community.general.pacman:
    name:
      - otf-font-awesome

- name: Ensure directory exists
  ansible.builtin.file:
    path: ~/.config/i3status-rust/
    state: directory
    mode: 0755

- name: Template status config
  ansible.builtin.template:
    src: config.toml
    dest: ~/.config/i3status-rust/config.toml
    mode: 0644
