---
- name: Install npm
  become: true
  become_user: root
  community.general.pacman:
    name:
      - npm

# TODO: Installing packages globally as root is just plain ugly.
- community.general.npm:
    name: js-beautify
    global: yes
  when: npm_install_packages
  become: true
  become_user: root

- community.general.npm:
    name: sass
    global: yes
  when: npm_install_packages
  become: true
  become_user: root

- community.general.npm:
    name: jslint
    global: yes
  when: npm_install_packages
  become: true
  become_user: root
