---
- name: Install vagrant
  become: true
  become_user: root
  community.general.pacman:
    name:
      - vagrant

- name: Install vagrant-libvirt plugin
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.command: vagrant plugin install vagrant-libvirt
  changed_when: true
  when: vars.vagrant.provider == "libvirt"

- name: Install vagrant plugins
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.command: vagrant plugin install "{{ item }}"
  changed_when: true
  loop:
    - vagrant-disksize
    - vagrant-cachier

- name: Ensure directory exists
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.file:
    path: ~/archlinux_vm
    state: directory
    mode: 0755
  when: vars.vagrant.prepare_archlinux_vm

- name: Copy Vagrantfile
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.copy:
    src: Vagrantfile
    dest: ~/archlinux_vm/
    mode: 0644
  when: vars.vagrant.prepare_archlinux_vm
