---
- name: Install vagrant
  become: true
  become_user: root
  community.general.pacman:
    name:
      - vagrant

- name: Get list of vagrant plugins
  ansible.builtin.command: vagrant plugin list
  changed_when: false
  register: vagrant_plugins

- name: Install vagrant-libvirt plugin
  ansible.builtin.command: vagrant plugin install vagrant-libvirt
  changed_when: true
  when: vars.vagrant_provider == "libvirt" and "vagrant-libvirt" not in vagrant_plugins.stdout

- name: Install vagrant plugins
  ansible.builtin.command: vagrant plugin install "{{ item }}"
  changed_when: true
  when: item not in vagrant_plugins.stdout
  loop:
    - vagrant-disksize
    - vagrant-cachier

- name: Ensure directory exists
  ansible.builtin.file:
    path: ~/arch_vm
    state: directory
    mode: 0755
  when: vars.vagrant_prepare_archlinux_vm

- name: Copy Vagrantfile
  ansible.builtin.template:
    src: Vagrantfile
    dest: ~/arch_vm/
    mode: 0644
  when: vars.vagrant_prepare_archlinux_vm

- name: Copy arch_vm README
  ansible.builtin.copy:
    src: README.md
    dest: ~/arch_vm/
    mode: 0644
  when: vars.vagrant_prepare_archlinux_vm

- name: Template fish plugin
  ansible.builtin.include_role:
    name: helper_fish_plugin
  vars:
    helper_fish_plugin_directory_name: vagrant
    helper_fish_plugin_template_name: vagrant.fish
