---
- name: Install opensnitch
  become: true
  become_user: root
  community.general.pacman:
    name:
      - opensnitch

- name: Start and enable opensnitchd
  become: true
  become_user: root
  ansible.builtin.systemd:
    name: opensnitchd
    enabled: true
    state: started

- name: Template sway plugin
  ansible.builtin.include_role:
    name: helper_sway_plugin
  vars:
    helper_sway_plugin_template_name: opensnitch-plugin
