---
- name: Install wayland
  become: true
  become_user: root
  community.general.pacman:
    name:
      - wayland
      # TODO: do we want to put it in a better place?
      - qt6-wayland
      # For pinentry-qt
      - kwayland5

- name: Enable wayland for Electron (system) apps
  ansible.builtin.copy:
    src: electron25-flags.conf
    dest: ~/.config/electron{{ item }}-flags.conf
    mode: 0644
  loop:
    - 25
    - 24
    - 23
    - 22
    - 21
    - 20

- name: Template fish plugin
  ansible.builtin.include_role:
    name: helper_fish_plugin
  vars:
    helper_fish_plugin_directory_name: wayland
    helper_fish_plugin_template_name: env.fish
