---
services_file: ~/.config/mailctl/services.yaml

# Store tokens in the GNOME keyring
ring_store:
  exec: secret-tool
  args:
    - store
    - --label

ring_lookup:
  exec: secret-tool
  args:
    - lookup
    - mailctl
