---
google:
  auth_endpoint: https://accounts.google.com/o/oauth2/auth
  auth_http_method: POST
  auth_params_mode: query-string
  token_endpoint: https://accounts.google.com/o/oauth2/token
  token_http_method: POST
  token_params_mode: both
  redirect_uri: http://localhost:8080
  # Only the first scope is strictly required
  # But for the sake of mail-pmi let's add all the scopes we might want
  auth_scope: https://mail.google.com/ https://www.googleapis.com/auth/carddav https://www.googleapis.com/auth/calendar
  client_id: {{mailctl_google_client_id}}
  client_secret: {{mailctl_google_client_secret}}
