---
- name: Install ranger and w3m (for image preview)
  become: true
  become_user: root
  community.general.pacman:
    name:
      - ranger
      - w3m

- name: Ensure directory exists
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.file:
    path: ~/.config/ranger
    state: directory
    mode: 0755

- name: Copy ranger config
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.copy:
    src: rc.conf
    dest: ~/.config/ranger/rc.conf
    mode: 0644
