---
- name: Install ranger
  become: true
  become_user: root
  pacman:
    name:
      - ranger

- name: Ensure directory exists
  become: true
  become_user: "{{ user.name }}"
  file:
    path: ~/.config/ranger
    state: directory
    recurse: yes

- name: Copy ranger config
  become: true
  become_user: "{{ user.name }}"
  copy:
      src: rc.conf
      dest: ~/.config/ranger/rc.conf
