---
- name: Install libvirt, dnsmasq, virt-manager and dmidecode
  become: true
  become_user: root
  community.general.pacman:
    name:
      - libvirt
      - dnsmasq
      - virt-manager
      - dmidecode
  register: install_packages

- name: Add user to libvirt group
  become: true
  become_user: root
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: libvirt
    state: present
    append: true

- name: Copy nftables config
  become: true
  become_user: root
  ansible.builtin.copy:
    src: libvirt-nft.conf
    dest: /etc/nftables.d/01-libvirt.conf
    mode: 0644
  register: nftables_config

- name: Reload nftables configuration
  become: true
  become_user: root
  ansible.builtin.systemd:
    name: nftables
    state: started
  when: nftables_config.changed  # noqa: no-handler

- name: Enable libvirtd
  become: true
  become_user: root
  ansible.builtin.systemd:
    name: libvirtd
    enabled: true

- name: Start libvirtd
  become: true
  become_user: root
  ansible.builtin.systemd:
    name: libvirtd
    state: started
  when: install_packages.changed  # noqa: no-handler
