---
- name: Install libvirt, dnsmasq, virt-manager and dmidecode
  become: true
  become_user: root
  community.general.pacman:
    name:
      - libvirt
      - dnsmasq
      - virt-manager
      - dmidecode

- name: Add user to libvirt group
  become: true
  become_user: root
  ansible.builtin.user:
    name: "{{ user_name }}"
    groups: libvirt
    state: present
    append: true

- name: Start and enable libvirtd
  become: true
  become_user: root
  ansible.builtin.systemd:
    name: libvirtd
    enabled: true
    state: started
