---
- name: Install libvirt, dnsmasq, virt-manager and dmidecode
  become: true
  become_user: root
  community.general.pacman:
    name:
      - libvirt
      - dnsmasq
      - virt-manager
      - dmidecode
  register: install_packages

- name: Add user to libvirt group
  become: true
  become_user: root
  ansible.builtin.user:
    name: "{{ user_name }}"
    groups: libvirt
    state: present
    append: true

- name: Enable libvirtd
  become: true
  become_user: root
  ansible.builtin.systemd:
    name: libvirtd
    enabled: true

- name: Start libvirtd
  become: true
  become_user: root
  ansible.builtin.systemd:
    name: libvirtd
    state: started
  when: install_packages.changed  # noqa: no-handler
