---
- name: Install picom
  become: true
  become_user: root
  pacman:
    name:
      - picom

- name: Ensure directory exists
  become: true
  become_user: "{{ user.name }}"
  file:
    path: /home/{{ user.name }}/.config
    state: directory
    recurse: yes

- name: Copy picom dotfile
  become: true
  become_user: "{{ user.name }}"
  copy:
      src: picom.conf
      dest: /home/{{ user.name }}/.config/picom.conf
