# Global values
# output=<undefined>#
min-width=320
max-width=320
max-height=320
# play-sound=aplay ${filename}

# layer=top
background=3f3f3fff # dark gray

border-color=6ca0a3ff # muted teal
border-radius=10
border-size=2

# padding-vertical=20
# padding-horizontal=20

dpi-aware=yes

title-font=Hack
title-color=6ca0a3ff # muted teal
# title-format=<i>%a%A</i>

summary-font=Hack
summary-color=ffffffff # white
# summary-format=<b>%s</b>\n

body-font=Hack
body-color=dcdcccff # warm off-white
# body-format=%b

# progress-bar-height=20
# progress-color=ffffffff
# progress-style=bar

# sound-file=
# icon=

# Timeout values are in seconds. 0 to disable
max-timeout=10
# default-timeout=10
idle-timeout=0
