---
- name: Install i3-gaps
  become: true
  become_user: root
  community.general.pacman:
    name:
      - i3-gaps

- name: Ensure directory exists
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.file:
    path: ~/.config/i3/
    state: directory
    recurse: true

- name: Copy scripts directory
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.copy:
    src: scripts
    dest: ~/.config/i3/

- name: Copy wallpapers
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.copy:
      src: wallpapers/{{ i3_resolution }}/
      dest: ~/.config/i3/wallpapers

- name: Template i3 config
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.template:
      src: config
      dest: ~/.config/i3/config

- name: Copy xinitrc
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.template:
    src: xinitrc
    dest: ~/.xinitrc
  when: i3_copy_xinitrc

- name: NOPASSWD sudo for g751 i3 scripts
  become: true
  become_user: root
  ansible.builtin.lineinfile:
    dest: /etc/sudoers.d/13-g751-scripts
    line: "{{ user.name }} ALL=(root) NOPASSWD: ~/.config/i3/scripts/g751/*
"
    create: true
    validate: 'visudo -cf %s'
  when: i3_nopasswd_g751_scripts

- name: Set script as executable
  ansible.builtin.file: dest=~/.config/i3/scripts/g751/change_brightness mode=a+x
  when: i3_setup_g751_scripts
