---
- name: Install nftables, firewalld and opensnitch
  become: true
  become_user: root
  community.general.pacman:
    name:
      - nftables
      - opensnitch

- name: Install ebpf module for opensnitch
  kewlfft.aur.aur:
    name:
      - opensnitch-ebpf-module
    state: present
  become: true
  become_user: aur_builder

- name: Enable nftables
  become: true
  become_user: root
  ansible.builtin.systemd:
    name: nftables
    enabled: true

- name: Start and enable opensnitchd
  become: true
  become_user: root
  ansible.builtin.systemd:
    name: opensnitchd
    enabled: true
    state: started
