---
- name: Install nftables
  become: true
  become_user: root
  community.general.pacman:
    name:
      - nftables
  register: nftables_install

- name: Install opensnitch
  become: true
  become_user: root
  community.general.pacman:
    name:
      - opensnitch
  when: vars.firewall_enable_opensnitch

- name: Install ebpf module for opensnitch
  kewlfft.aur.aur:
    name:
      - opensnitch-ebpf-module
    state: present
  become: true
  become_user: aur_builder
  when: vars.firewall_enable_opensnitch

- name: Enable nftables
  become: true
  become_user: root
  ansible.builtin.systemd:
    name: nftables
    enabled: true

- name: Template nftables.conf
  become: true
  become_user: root
  ansible.builtin.template:
    src: base.conf
    dest: /etc/nftables.conf
    mode: 0644
  register: nftables_config

- name: Ensure append directory exists
  become: true
  become_user: root
  ansible.builtin.file:
    path: /etc/nftables.d
    state: directory
    mode: 0755

- name: Copy nftables counter append
  become: true
  become_user: root
  ansible.builtin.copy:
    src: counter.conf
    dest: /etc/nftables.d/99-counter.conf
    mode: 0644
  register: nftables_counter

- name: Reload nftables configuration
  become: true
  become_user: root
  ansible.builtin.systemd:
    name: nftables
    state: started
  when: nftables_install.changed or nftables_config.changed or nftables_counter.changed

- name: Start and enable opensnitchd
  become: true
  become_user: root
  ansible.builtin.systemd:
    name: opensnitchd
    enabled: true
    state: started
  when: vars.firewall_enable_opensnitch

- name: Template sway plugin
  ansible.builtin.include_role:
    name: helper_sway_plugin
  vars:
    helper_sway_plugin_template_name: opensnitch-plugin
