---
- name: Install i3lock
  become: true
  become_user: root
  community.general.pacman:
    name:
      - i3lock

- name: Copy suspend service file
  become: true
  become_user: root
  ansible.builtin.copy:
    src: suspend@.service
    dest: /etc/systemd/system/
    mode: 0644

- name: Copy resume service file
  become: true
  become_user: root
  ansible.builtin.copy:
    src: resume@.service
    dest: /etc/systemd/system/
    mode: 0644

- name: Enable suspend service file
  become: true
  become_user: root
  ansible.builtin.systemd:
    name: suspend@{{ user.name }}
    enabled: true

- name: Enable resume service file
  become: true
  become_user: root
  ansible.builtin.systemd:
    name: resume@{{ user.name }}
    enabled: true
