---
- name: Install i3lock
  become: true
  become_user: root
  community.general.pacman:
    name:
      - i3lock

- name: Copy suspend service file
  become: true
  become_user: root
  ansible.builtin.copy:
    src: suspend-i3lock@.service
    dest: /etc/systemd/system/
    mode: 0644

- name: Enable suspend service file
  become: true
  become_user: root
  ansible.builtin.systemd:
    name: suspend-i3lock@{{ user_name }}
    enabled: true

- name: Template the wrapper file
  become: true
  become_user: root
  ansible.builtin.template:
    src: i3lock-arch-ansible
    dest: /usr/local/bin/i3lock-arch-ansible
    mode: 0755

- name: Properly bootstrap wallpaper
  when: vars.i3lock_wallpaper
  block:
    - name: Ensure directory exists
      become: true
      become_user: "{{ user_name }}"
      ansible.builtin.file:
        path: ~/.config/i3lock/wallpapers
        state: directory
        mode: 0755

    # Commands that don't change the "important" state are marked as non-changeable
    - name: Create temporary directory
      ansible.builtin.tempfile:
        state: directory
        suffix: i3lock
      register: i3lock_tempdir
      changed_when: false

    - name: Copy the base wallpaper
      become: true
      become_user: "{{ user_name }}"
      ansible.builtin.copy:
        src: wallpapers/{{ vars.i3lock_wallpaper }}
        dest: "{{ i3lock_tempdir.path }}/wallpaper"
        mode: 0644
      changed_when: false

    - name: Resize and remove metadata
      # Resize image and get rid of metadata
      # so the hashes are deterministic
      become: true
      become_user: "{{ user_name }}"
      ansible.builtin.command:
        chdir: "{{ i3lock_tempdir.path }}"
        # The resize ! parameter allows changing ratio
        cmd: convert wallpaper -strip -resize "{{ vars.display_resolution }}!" wallpaper-resized
      changed_when: false

    - name: Remove metadata (exiftool)
      # For whatever reason imagemagick leaves png:tIME on some images
      # exiftool handles it properly
      become: true
      become_user: "{{ user_name }}"
      ansible.builtin.command:
        chdir: "{{ i3lock_tempdir.path }}"
        cmd: exiftool -all= wallpaper-resized
      changed_when: false

    - name: Copy the modified wallpaper
      become: true
      become_user: "{{ user_name }}"
      ansible.builtin.copy:
        src: "{{ i3lock_tempdir.path }}/wallpaper-resized"
        dest: ~/.config/i3lock/wallpapers/{{ vars.i3lock_wallpaper }}
        mode: 0644
