---
- name: Install git
  become: true
  become_user: root
  community.general.pacman:
    name:
      - git

- name: Install hub
  become: true
  become_user: root
  community.general.pacman:
    name:
      - hub
  when: git_install_hub

- name: Install diff-so-fancy and less
  become: true
  become_user: root
  community.general.pacman:
    name:
      - diff-so-fancy
      - less

- name: Ensure directory exists
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.file:
    path: ~/.config/i3/
    state: directory
    mode: 0755

- name: Copy global excludesfile
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.copy:
    src: gitignore_global
    dest: ~/.gitignore_global
    mode: 0644

- name: Set up gitconfig
  become: true
  become_user: "{{ user.name }}"
  block:
    - name: Set git user.email
      community.general.git_config:
        name: user.email
        scope: global
        value: "{{ user.email }}"

    - name: Set git user.name
      community.general.git_config:
        name: user.name
        scope: global
        value: "{{ user.pub_name }}"

    - name: Set git excludesFile
      community.general.git_config:
        name: core.excludesfile
        scope: global
        value: "~/.gitignore_global"

    - name: Set git pager (diff-so-fancy)
      community.general.git_config:
        name: core.pager
        scope: global
        value: "diff-so-fancy | less --tabs=4 -RFX"

    - name: Set git diffFilter (diff-so-fancy)
      community.general.git_config:
        name: interactive.diffFilter
        scope: global
        value: "diff-so-fancy --patch"

    - name: Set git diff-so-fancy options
      community.general.git_config:
        name: diff-so-fancy.markEmptyLines
        scope: global
        value: "false"
