---
- name: Install git
  become: true
  become_user: root
  community.general.pacman:
    name:
      - git

- name: Install hub
  become: true
  become_user: root
  community.general.pacman:
    name:
      - hub
  when: git_install_hub

- name: Install diff-so-fancy and less
  become: true
  become_user: root
  community.general.pacman:
    name:
      - diff-so-fancy
      - less

- block:
  - community.general.git_config:
     name: user.email
     scope: global
     value: "{{ user.email }}"

  - community.general.git_config:
     name: user.name
     scope: global
     value: "{{ user.pub_name }}"

  - community.general.git_config:
     name: core.pager
     scope: global
     value: "diff-so-fancy | less --tabs=4 -RFX"

  - community.general.git_config:
     name: interactive.diffFilter
     scope: global
     value: "diff-so-fancy --patch"

  - community.general.git_config:
     name: diff-so-fancy.markEmptyLines
     scope: global
     value: "false"

  become: yes
  become_user: "{{ user.name }}"
