---
- name: Install git and git-lfs
  become: true
  become_user: root
  community.general.pacman:
    name:
      - git
      - git-lfs

- name: Install sendemail SSL dependencies
  become: true
  become_user: root
  when: git_smtp_password | length > 0
  community.general.pacman:
    name:
      - perl-authen-sasl
      - perl-io-socket-ssl

- name: Install hub
  become: true
  become_user: root
  community.general.pacman:
    name:
      - hub
  when: git_install_hub

- name: Install diff-so-fancy and less
  become: true
  become_user: root
  community.general.pacman:
    name:
      - diff-so-fancy
      - less

- name: Ensure directory exists
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.file:
    path: ~/.config/i3/
    state: directory
    mode: 0755

- name: Copy global excludesfile
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.copy:
    src: gitignore_global
    dest: ~/.gitignore_global
    mode: 0644

- name: Set up gitconfig
  become: true
  become_user: "{{ user_name }}"
  block:
    - name: Set git user.email
      community.general.git_config:
        name: user.email
        scope: global
        value: "{{ user_email }}"

    - name: Set git user.name
      community.general.git_config:
        name: user.name
        scope: global
        value: "{{ user_pub_name }}"

    - name: Set git excludesFile
      community.general.git_config:
        name: core.excludesfile
        scope: global
        value: "~/.gitignore_global"

    - name: Set git pager (diff-so-fancy)
      community.general.git_config:
        name: core.pager
        scope: global
        value: "diff-so-fancy | less --tabs=4 -RFX"

    - name: Set git diffFilter (diff-so-fancy)
      community.general.git_config:
        name: interactive.diffFilter
        scope: global
        value: "diff-so-fancy --patch"

    - name: Set git diff-so-fancy options
      community.general.git_config:
        name: diff-so-fancy.markEmptyLines
        scope: global
        value: "false"

- name: Set up sendmail
  become: true
  become_user: "{{ user_name }}"
  block:
    - name: Set server
      community.general.git_config:
        name: sendemail.smtpserver
        scope: global
        value: "{{ git_smtp_server }}"

    - name: Set user
      community.general.git_config:
        name: sendemail.smtpuser
        scope: global
        value: "{{ git_smtp_user }}"

    - name: Set encryption
      community.general.git_config:
        name: sendemail.smtpencryption
        scope: global
        value: "{{ git_smtp_encryption }}"

    - name: Set serverport
      community.general.git_config:
        name: sendemail.smtpserverport
        scope: global
        value: "{{ git_smtp_serverport }}"

    - name: Set the confirmation level
      community.general.git_config:
        name: sendemail.confirm
        scope: global
        value: "{{ git_sendemail_confirm }}"

    - name: Set the password
      # TODO: switch to using a proper credentials helper
      # GPG / bitwarden?
      # Relying on a file with restricted permissions is not safe at all
      block:
        - name: Ensure the password file has correct permissions
          ansible.builtin.file:
            path: "{{ git_sendemail_password_file }}"
            mode: 0600
            state: touch
            modification_time: preserve
            access_time: preserve

        - name: Set password in a separate file
          # We allow the user to set the password outside of the
          # arch_ansible ecosystem
          when: git_smtp_password | length > 0
          community.general.git_config:
            file: "{{ git_sendemail_password_file }}"
            name: sendemail.smtpPass
            scope: file
            value: "{{ git_smtp_password }}"

    - name: Include the password file
      community.general.git_config:
        name: include.path
        scope: global
        value: "{{ git_sendemail_password_file }}"

- name: Set up fish scriptlets
  when: fish_install_extensions
  block:
    - name: Ensure directory exists
      ansible.builtin.file:
        path: ~/.config/fish/ansible/git
        state: directory
        mode: 0755

    - name: Template scriptlet
      ansible.builtin.template:
        src: git.fish
        dest: ~/.config/fish/ansible/git/git.fish
        mode: 0644
