---
- name: Install git and git-lfs
  become: true
  become_user: root
  community.general.pacman:
    name:
      - git
      - git-lfs

- name: Install hub
  become: true
  become_user: root
  community.general.pacman:
    name:
      - hub
  when: git_install_hub

- name: Install diff-so-fancy and less
  become: true
  become_user: root
  community.general.pacman:
    name:
      - diff-so-fancy
      - less

- name: Ensure directory exists
  ansible.builtin.file:
    path: ~/.config/i3/
    state: directory
    mode: 0755

- name: Copy global excludesfile
  ansible.builtin.copy:
    src: gitignore_global
    dest: ~/.gitignore_global
    mode: 0644

- name: Set up gitconfig
  block:
    - name: Set git user.email
      community.general.git_config:
        name: user.email
        scope: global
        value: "{{ git_email }}"

    - name: Set git user.name
      community.general.git_config:
        name: user.name
        scope: global
        value: "{{ git_username }}"

    - name: Set git excludesFile
      community.general.git_config:
        name: core.excludesfile
        scope: global
        value: "~/.gitignore_global"

    - name: Set git pager (diff-so-fancy)
      community.general.git_config:
        name: core.pager
        scope: global
        value: "diff-so-fancy | less --tabs=4 -RFX"

    - name: Set git diffFilter (diff-so-fancy)
      community.general.git_config:
        name: interactive.diffFilter
        scope: global
        value: "diff-so-fancy --patch"

    - name: Set git diff-so-fancy options
      community.general.git_config:
        name: diff-so-fancy.markEmptyLines
        scope: global
        value: "false"

- name: Set up sendmail
  block:
    - name: Set sendmail command
      community.general.git_config:
        name: sendemail.sendmailCmd
        scope: global
        value: "{{ git_sendemail_command }} --account={{ git_sendemail_mailbox }} --from='{{ git_sendemail_from }}'"

    - name: Set the confirmation level
      community.general.git_config:
        name: sendemail.confirm
        scope: global
        value: "{{ git_sendemail_confirm }}"

- name: Template fish plugin
  ansible.builtin.include_role:
    name: helper_fish_plugin
  vars:
    helper_fish_plugin_directory_name: git
    helper_fish_plugin_template_name: git.fish
