---
- name: Install git
  become: true
  become_user: root
  pacman:
    name:
      - git

- name: Install hub
  become: true
  become_user: root
  pacman:
    name:
      - hub
  when: git_install_hub

- block:
  - git_config:
     name: user.email
     scope: global
     value: "{{ user.email }}"

  - git_config:
     name: user.name
     scope: global
     value: "{{ user.pub_name }}"
  become: yes
  become_user: "{{ user.name }}"
