---
- name: Get rid of flameshot
  ansible.builtin.include_tasks:
    file: flameshot-cleanup.yml

- name: Get rid of grimshot package from AUR
  become: true
  become_user: root
  community.general.pacman:
    name:
      - grimshot
    state: absent

- name: Install the optdepends and sway-contrib
  become: true
  become_user: root
  community.general.pacman:
    name:
      - wl-clipboard
      - sway-contrib

- name: Symlink the grimshot script so it's in PATH
  become: true
  become_user: root
  ansible.builtin.file:
    src: "/usr/share/sway-contrib/grimshot"
    dest: "/usr/local/bin/grimshot"
    state: link

- name: Ensure directory exists
  ansible.builtin.file:
    path: ~/.config/sway/scripts/grimshot/
    state: directory
    mode: 0755

- name: Template the helper script
  ansible.builtin.template:
    src: screenshot-filename.sh
    dest: ~/.config/sway/scripts/grimshot/find_filename.sh
    mode: 0755

- name: Template sway plugin
  ansible.builtin.include_role:
    name: helper_sway_plugin
  vars:
    helper_sway_plugin_template_name: grimshot-plugin
