---
- name: Install dunst
  become: true
  become_user: root
  community.general.pacman:
    name:
      - dunst

- name: Ensure directory exists
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.file:
    path: ~/.config/dunst
    state: directory
    mode: 0755

- name: Copy dunst dotfile
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.copy:
    src: dunstrc
    dest: ~/.config/dunst/dunstrc
    mode: 0644
