---
- name: Install dunst
  become: true
  become_user: root
  pacman:
    name:
      - dunst

- name: Ensure directory exists
  become: true
  become_user: "{{ user.name }}"
  file:
    path: ~/.config/dunst
    state: directory
    recurse: yes

- name: Copy dunst dotfile
  become: true
  become_user: "{{ user.name }}"
  copy:
      src: dunstrc
      dest: ~/.config/dunst/dunstrc
