" Generated by vim-plug
" Sun 06 Aug 2023 04:22:40 AM CEST
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['SimpylFold'].commit = 'ff4c85197c5555715093c08a8d4f9d493c4d80cd'
silent! let g:plugs['Zenburn'].commit = '8df765342b2a33c728ce147d6c8e66359378f9d5'
silent! let g:plugs['ale'].commit = '15cbc0e912acf31d8185dbef00473e9555591350'
silent! let g:plugs['indentpython.vim'].commit = '6aaddfde21fe9e7acbe448b92b3cbb67f2fe1fc1'
silent! let g:plugs['nerdtree'].commit = 'c46e12a886b4a6618a9e834c90f6245952567115'
silent! let g:plugs['nerdtree-git-plugin'].commit = 'e1fe727127a813095854a5b063c15e955a77eafb'
silent! let g:plugs['open-browser.vim'].commit = '7d4c1d8198e889d513a030b5a83faa07606bac27'
silent! let g:plugs['plantuml-previewer.vim'].commit = '1dd4d0f2b09cd80a217f76d82f93830dbbe689b3'
silent! let g:plugs['plantuml-syntax'].commit = '845abb56dcd3f12afa6eb47684ef5ba3055802b8'
silent! let g:plugs['tabular'].commit = '339091ac4dd1f17e225fe7d57b48aff55f99b23a'
silent! let g:plugs['vim-airline'].commit = 'e6bb8427dc2d2dc3583ed1bf5ff6a9682c854d32'
silent! let g:plugs['vim-autoformat'].commit = '7b35295b519f5f69be2e10b936db7fbac290b813'
silent! let g:plugs['vim-markdown'].commit = 'cc82d88e2a791f54d2b6e2b26e41f743351ac947'
silent! let g:plugs['vim-obsession'].commit = 'fe9d3e1a9a50171e7d316a52e1e56d868e4c1fe5'
silent! let g:plugs['vim-polyglot'].commit = 'bc8a81d3592dab86334f27d1d43c080ebf680d42'
silent! let g:plugs['vimtex'].commit = '877de3ba5de5f766e5bfa1c3fb0d2ecfcd18f868'

" PlugUpdate!
