" Generated by vim-plug
" Sun 23 Feb 2025 11:51:06 PM CET
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['SimpylFold'].commit = 'ff4c85197c5555715093c08a8d4f9d493c4d80cd'
silent! let g:plugs['Zenburn'].commit = '8df765342b2a33c728ce147d6c8e66359378f9d5'
silent! let g:plugs['ale'].commit = '699c0dbe80e4395370a4d2dc9816a4d18d85371f'
silent! let g:plugs['indentpython.vim'].commit = '6aaddfde21fe9e7acbe448b92b3cbb67f2fe1fc1'
silent! let g:plugs['nerdtree'].commit = '9b465acb2745beb988eff3c1e4aa75f349738230'
silent! let g:plugs['nerdtree-git-plugin'].commit = 'e1fe727127a813095854a5b063c15e955a77eafb'
silent! let g:plugs['open-browser.vim'].commit = '7d4c1d8198e889d513a030b5a83faa07606bac27'
silent! let g:plugs['plantuml-previewer.vim'].commit = '368a1f331c1ff29f6a3ee76facfca39a7f374b13'
silent! let g:plugs['plantuml-syntax'].commit = '9d4900aa16674bf5bb8296a72b975317d573b547'
silent! let g:plugs['tabular'].commit = '12437cd1b53488e24936ec4b091c9324cafee311'
silent! let g:plugs['vim-airline'].commit = '7a552f415c48aed33bf7eaa3c50e78504d417913'
silent! let g:plugs['vim-autoformat'].commit = 'e89c47a89909a69c4b4426a71e99c197adae7a44'
silent! let g:plugs['vim-markdown'].commit = '8f6cb3a6ca4e3b6bcda0730145a0b700f3481b51'
silent! let g:plugs['vim-obsession'].commit = 'ed9dfc7c2cc917ace8b24f4f9f80a91e05614b63'
silent! let g:plugs['vim-polyglot'].commit = 'f5393cfee07aeb666f4d75f9b3a83163862fb094'
silent! let g:plugs['vimtex'].commit = '63ae2e94b0fabc6bdad0a685c1ef0a7e0705fe7b'

" PlugUpdate!
