---
- name: Install Emacs (>=28)
  aur: 
    skip_installed: true
    name: 
      - emacs-git
  become: yes
  become_user: aur_builder

- name: Copy Emacs config
  become: true
  become_user: "{{ user.name }}"
  copy:
    src: emacs
    dest: /home/{{ user.name }}/.emacs

- name: Set up Emacs
  become: true
  become_user: "{{ user.name }}"
  shell: yes | emacs --script /home/{{ user.name }}/.emacs
