---
- name: Install Emacs (>=28)
  aur:
    state: present
    name:
      - emacs-git
  become: yes
  become_user: aur_builder

- name: Create the .emacs.d dir
  become: true
  become_user: "{{ user.name }}"
  file: path=~/.emacs.d state=directory

# That's the stable release as of 15/06/2021
- name: Get the straight.el as git repo (security + issues with GNUtls)
  become: true
  become_user: "{{ user.name }}"
  git:
    dest: /home/{{ user.name}}/.emacs.d/straight/repos/straight.el
    repo: https://github.com/raxod502/straight.el.git
    version: 1e27b0590df77a5d478970ca58fd6606971692f5

- name: Copy Emacs early config
  become: true
  become_user: "{{ user.name }}"
  copy:
    src: early-init.el
    dest: ~/.emacs.d/early-init.el

- name: Copy Emacs config
  become: true
  become_user: "{{ user.name }}"
  copy:
    src: emacs
    dest: ~/.emacs

- name: Create the straight.el dir
  become: true
  become_user: "{{ user.name }}"
  file: path=~/.emacs.d/straight/versions state=directory

- name: Copy straight.el lockfile
  become: true
  become_user: "{{ user.name }}"
  copy:
    src: default.el
    dest: ~/.emacs.d/straight/versions/default.el

- name: Set up Emacs
  become: true
  become_user: "{{ user.name }}"
  shell: yes | emacs --script ~/.emacs
