---
- name: Install Emacs (>=28)
  kewlfft.aur.aur:
    state: present
    name:
      - emacs-git
  become: true
  become_user: aur_builder
  register: var_emacs_installed

- name: Create the .emacs.d dir
  ansible.builtin.file:
    path: ~/.emacs.d
    state: directory
    mode: 0755

# That's the stable release as of 15/06/2021
- name: Get the straight.el as git repo (security + issues with GNUtls)
  ansible.builtin.git:
    dest: ~/.emacs.d/straight/repos/straight.el
    repo: https://github.com/raxod502/straight.el.git
    version: 1e27b0590df77a5d478970ca58fd6606971692f5
  register: var_emacs_straight_git

- name: Copy Emacs early config
  ansible.builtin.copy:
    src: early-init.el
    dest: ~/.emacs.d/early-init.el
    mode: 0644

- name: Copy Emacs config
  ansible.builtin.copy:
    src: emacs
    dest: ~/.emacs
    mode: 0644
  register: var_emacs_config

- name: Create the straight.el dir
  ansible.builtin.file:
    path: ~/.emacs.d/straight/versions
    state: directory
    mode: 0755

- name: Copy straight.el lockfile
  ansible.builtin.copy:
    src: default.el
    dest: ~/.emacs.d/straight/versions/default.el
    mode: 0644
  register: var_emacs_lockfile

- name: Install plugins
  ansible.builtin.shell: set -o pipefail && yes | emacs --script ~/.emacs
  args:
    executable: /usr/bin/env bash
  changed_when: true
  when: var_emacs_straight_git.changed or var_emacs_config.changed or var_emacs_lockfile.changed or var_emacs_installed.changed
