---
- name: Install Zoom from AUR
  kewlfft.aur.aur:
    name:
      - zoom
    state: present
  become: true
  become_user: aur_builder

# TODO: template the config file (it's kinda long and messed up) and set enableWaylandShare=true in the [General] section
