---
- name: Install Python3 and pip
  become: true
  become_user: root
  pacman:
    name:
      - python3
      - python-pip


- name: Install Python3 packages
  become: true
  become_user: root
  pacman:
    name:
      - python-pynvim
      - mypy
      - python-pylint
      - python-pytest
