---
- name: Install Python3, pip and pyenv
  become: true
  become_user: root
  community.general.pacman:
    name:
      - python3
      - python-pip
      - pyenv

- name: Install Python3 packages
  become: true
  become_user: root
  community.general.pacman:
    name:
      - python-pynvim
      - mypy
      - python-pylint
      - python-pytest
      - python-poetry
      - python-pipx
      - python-pre-commit

- name: Ensure directory exists
  ansible.builtin.file:
    path: ~/.config/pypoetry/
    state: directory
    mode: 0755

- name: Copy poetry config
  ansible.builtin.copy:
    src: pypoetry-config.toml
    dest: ~/.config/pypoetry/config.toml
    mode: 0644

- name: Template fish plugin
  ansible.builtin.include_role:
    name: helper_fish_plugin
  vars:
    helper_fish_plugin_directory_name: python3
    helper_fish_plugin_template_name: pyenv.fish
