---
- name: Install Python3, pip and pyenv
  become: true
  become_user: root
  pacman:
    name:
      - python3
      - python-pip
      - pyenv

- name: Install Python3 packages
  become: true
  become_user: root
  pacman:
    name:
      - python-pynvim
      - mypy
      - python-pylint
      - python-pytest
      - python-poetry
