---
- name: Install yubikey tooling
  become: true
  become_user: root
  community.general.pacman:
    name:
      - yubikey-manager
      - yubikey-manager-qt
      - yubikey-personalization-gui
      - hopenpgp-tools
      - libfido2

- name: Install Yubico Authenticator from AUR
  kewlfft.aur.aur:
    name:
      - yubico-authenticator-bin
    state: present
  become: true
  become_user: aur_builder

- name: Enable pcscd.service
  become: true
  become_user: root
  ansible.builtin.systemd:
    name: pcscd
    enabled: true

- name: Ensure directory exists
  become: true
  become_user: root
  ansible.builtin.file:
    path: /etc/polkit-1/rules.d
    state: directory
    mode: 0755

- name: Copy polkit rules for pcscd
  become: true
  become_user: root
  ansible.builtin.copy:
    src: 99-pcscd.rules
    dest: /etc/polkit-1/rules.d/99-pcscd.rules
    mode: 0644
  register: polkit_rules

- name: Restart polkit service
  become: true
  become_user: root
  ansible.builtin.systemd:
    name: polkit
    state: "{{ (polkit_rules.changed) | ternary('restarted', 'started') }}"

- name: Copy gpg_ scripts
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "~/scripts/gpg"
    mode: 0755
  loop:
    - scripts/gpg_yubikey_initial_setup.sh
    - scripts/gpg_yubikey_keytocard.sh

- name: Template sway plugin
  ansible.builtin.include_role:
    name: helper_sway_plugin
  vars:
    helper_sway_plugin_template_name: yubikey-plugin
