---
- name: Install Go
  become: true
  become_user: root
  pacman:
    name:
      - go

- name: Go install few tools
  become: yes
  become_user: "{{ user.name }}"
  command: "{{ item }}"
  with_items:
    - go install golang.org/x/tools/cmd/godoc@latest
    - go install golang.org/x/lint/golint@latest
    - go install golang.org/x/tools/cmd/goimports@latest
    - go install github.com/nsf/gocode@latest
    - go install github.com/rogpeppe/godef@latest
    - go install github.com/kisielk/errcheck@latest
  when: go_install_packages
