---
- name: Install Go
  become: true
  become_user: root
  community.general.pacman:
    name:
      - go

# - name: Go install few tools
#   ansible.builtin.command: "{{ item }}"
#   with_items:
#     - go install golang.org/x/tools/cmd/godoc@latest
#     - go install golang.org/x/lint/golint@latest
#     - go install golang.org/x/tools/cmd/goimports@latest
#     - go install github.com/nsf/gocode@latest
#     - go install github.com/rogpeppe/godef@latest
#     - go install github.com/kisielk/errcheck@latest
#   when: go_install_packages
#   changed_when: true

- name: Template fish plugin
  ansible.builtin.include_role:
    name: helper_fish_plugin
  vars:
    helper_fish_plugin_directory_name: go
    helper_fish_plugin_template_name: env.fish
