---
- name: Install rofi
  become: true
  become_user: root
  pacman:
    name:
      - rofi

- name: Ensure directory exists
  become: true
  become_user: "{{ user.name }}"
  file:
    path: ~/.config/rofi
    state: directory
    recurse: yes

- name: Copy rofi config
  become: true
  become_user: "{{ user.name }}"
  copy:
    src: config.rasi
    dest: ~/.config/rofi/config.rasi

- name: Copy rofi spotlight-dark theme
  become: true
  become_user: "{{ user.name }}"
  copy:
    src: spotlight-dark.rasi
    dest: ~/.config/rofi/spotlight-dark.rasi
