---
- name: Install rofi
  become: true
  become_user: root
  community.general.pacman:
    name:
      - rofi

- name: Ensure directory exists
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.file:
    path: ~/.config/rofi
    state: directory
    recurse: true
    mode: 0755

- name: Copy rofi config
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.copy:
    src: config.rasi
    dest: ~/.config/rofi/config.rasi
    mode: 0644

- name: Copy rofi spotlight-dark theme
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.copy:
    src: spotlight-dark.rasi
    dest: ~/.config/rofi/spotlight-dark.rasi
    mode: 0644
