---
- name: Install rofi
  become: true
  become_user: root
  pacman:
    name:
      - rofi

- name: Ensure directory exists
  become: true
  become_user: "{{ user.name }}"
  file:
    path: ~/.config/rofi
    state: directory
    recurse: yes

- name: Copy rofi dotfile
  become: true
  become_user: "{{ user.name }}"
  copy:
      src: rofi_config
      dest: ~/.config/rofi/config.rasi
