---
- name: Remove rofi
  become: true
  become_user: root
  community.general.pacman:
    name:
      - rofi
    state: absent

- name: Install rofi fork with wayland support
  kewlfft.aur.aur:
    name:
      - rofi-lbonn-wayland
    state: present
  become: true
  become_user: aur_builder

- name: Ensure directory exists
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.file:
    path: ~/.config/rofi
    state: directory
    mode: 0755

- name: Copy rofi config
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.copy:
    src: config.rasi
    dest: ~/.config/rofi/config.rasi
    mode: 0644

- name: Copy rofi spotlight-dark theme
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.copy:
    src: spotlight-dark.rasi
    dest: ~/.config/rofi/spotlight-dark.rasi
    mode: 0644
