---
- name: Install sudo
  become: true
  become_user: root
  pacman:
    name: sudo
    state: latest
  tags:
      - install

- name: Add user to sudo group
  lineinfile:
    path: /etc/sudoers.d/10-user-sudo
    line: '%wheel ALL=(ALL) ALL'
    create: yes
    validate: 'visudo -cf %s'
  become: true
  become_user: root
  tags:
      - configure
