---
- name: Install tmux
  become: true
  become_user: root
  pacman:
    name:
      - tmux

- name: Ensure directory exists
  become: true
  become_user: "{{ user.name }}"
  file:
    path: ~/.tmux/plugins
    state: directory
    recurse: yes

- name: Clone tmux plugin manager
  become: true
  become_user: "{{ user.name }}"
  git:
    repo: https://github.com/tmux-plugins/tpm.git
    dest: ~/.tmux/plugins/tpm

- name: Ensure directory exists
  become: true
  become_user: "{{ user.name }}"
  file:
    path: "~"
    state: directory
    recurse: yes

- name: Copy tmux.conf
  become: true
  become_user: "{{ user.name }}"
  copy:
    src: tmux.conf
    dest: ~/.tmux.conf

- name: Install plugins
  become: true
  become_user: "{{ user.name }}"
  shell:
    cmd: tmux start-server && tmux new-session -d install_plugins && ~/.tmux/plugins/tpm/scripts/install_plugins.sh

# TODO: actually install plugins
