---
- name: Install tmux
  become: true
  become_user: root
  community.general.pacman:
    name:
      - tmux

- name: Ensure directory exists
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.file:
    path: ~/.tmux/plugins
    state: directory
    recurse: true

- name: Clone tmux plugin manager
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm.git
    dest: ~/.tmux/plugins/tpm
    version: v3.1.0
  register: var_tmux_tpm_git

- name: Ensure directory exists
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.file:
    path: "~"
    state: directory

- name: Copy tmux.conf
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.copy:
    src: tmux.conf
    dest: ~/.tmux.conf

- name: Copy tmux_plugins.conf
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.copy:
    src: tmux_plugins.conf
    dest: ~/.tmux_plugins.conf
  register: var_tmux_plugins

- name: Install plugins
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.shell:
    cmd: tmux start-server && tmux new-session -d install_plugins && ~/.tmux/plugins/tpm/scripts/install_plugins.sh
  when: var_tmux_plugins.changed or var_tmux_tpm_git.changed
  changed_when: true
