---
- name: Install kubectl, kubectx, helm
  become: true
  become_user: root
  community.general.pacman:
    name:
      - kubectl
      - kubectx
      - helm

- name: Install krew
  kewlfft.aur.aur:
    state: present
    name:
      - krew-bin
  become: true
  become_user: aur_builder

- name: Refresh krew repos
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.command: kubectl krew update
  changed_when: true

- name: Install plugins managed by krew
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.command: "{{ item }}"
  with_items:
    - kubectl krew install modify-secret
  changed_when: true
