---
- name: Install K8s tools
  become: true
  become_user: root
  community.general.pacman:
    name:
      - kubectl
      - kubectx
      - helm
      - helmfile
      - skaffold
      - k9s

- name: Install jq, yq
  become: true
  become_user: root
  community.general.pacman:
    name:
      - jq
      - yq

- name: Install helm plugins
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.command: helm plugin install "{{ item }}"
  with_items:
    - "https://github.com/databus23/helm-diff"
  register: helm_install_plugin
  changed_when: helm_install_plugin.rc == 0
  failed_when: (helm_install_plugin.rc not in [0,1]) or ((helm_install_plugin.rc == 1) and (not (helm_install_plugin.stderr | regex_search("Error.* plugin already exists"))))

- name: Install krew
  kewlfft.aur.aur:
    state: present
    name:
      - krew-bin
  become: true
  become_user: aur_builder
  register: krew_install

- name: Refresh krew repos
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.command: kubectl krew update
  changed_when: true
  when: krew_install.changed  # noqa: no-handler

- name: Install plugins managed by krew
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.command: kubectl krew install "{{ item }}"
  register: krew_install_plugin
  with_items:
    - modify-secret
    - resource-capacity
  changed_when: not (krew_install_plugin.stderr | regex_search("Skipping plugin .* it is already installed"))

- name: Ensure fish directory exists
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.file:
    path: ~/.config/fish/ansible/kubectl_stuff
    state: directory
    mode: 0700
  when: fish_install_extensions

- name: Copy fish config
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.copy:
    src: kubernetes.fish
    dest: ~/.config/fish/ansible/kubectl_stuff/kubernetes.fish
    mode: 0644
  when: fish_install_extensions
