---
- name: Install foot
  become: true
  become_user: root
  community.general.pacman:
    name:
      - foot
      - foot-terminfo

- name: Ensure directory exists
  ansible.builtin.file:
    path: ~/.config/foot/
    state: directory
    mode: 0755

- name: Template the config
  ansible.builtin.template:
    src: foot.ini
    dest: ~/.config/foot/foot.ini
    mode: 0644
