---
- name: Install msmtp
  become: true
  become_user: root
  community.general.pacman:
    name:
      - msmtp

- name: Template config file
  ansible.builtin.template:
    src: msmtprc
    dest: ~/.msmtprc
    mode: 0600
