---
- name: Create user
  ansible.builtin.user:
    name: "{{ user.name }}"
    generate_ssh_key: '{{ user.generate_ssh_key | default(true) }}'
    ssh_key_bits: '{{ user.ssh_key_bits | default(omit) }}'
    ssh_key_type: '{{ user.ssh_key_type | default(omit) }}'
    groups: wheel
    state: present
    append: true
