---
- name: Install openssh (for ssh-keygen)
  become: true
  become_user: root
  community.general.pacman:
    name:
      - openssh
  when: vars.user.generate_ssh_key

- name: Create user
  ansible.builtin.user:
    name: "{{ user.name }}"
    generate_ssh_key: '{{ user.generate_ssh_key }}'
    ssh_key_type: '{{ user.ssh_key_type }}'
    groups: wheel
    state: present
    append: true

- name: Create basic directory tree
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - ~/Pictures/screenshots
    - ~/Documents
    - ~/Downloads
    - ~/Videos
