---
- name: Create user
  ansible.builtin.user:
    name: "{{ user.name }}"
    generate_ssh_key: '{{ user.generate_ssh_key }}'
    ssh_key_type: '{{ user.ssh_key_type }}'
    groups: wheel
    state: present
    append: true
