---
- name: Install docker and buildx
  become: true
  become_user: root
  community.general.pacman:
    name:
      - docker
      - docker-buildx

- name: Start and enable docker service
  become: true
  become_user: root
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: docker

- name: Add user to docker group
  become: true
  become_user: root
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: docker
    state: present
    append: true

- name: Copy nftables config
  become: true
  become_user: root
  ansible.builtin.template:
    src: docker-nft.conf
    dest: /etc/nftables.d/01-docker.conf
    mode: 0644
  notify:
    - Reload nftables
