---
- name: Install docker
  become: true
  become_user: root
  community.general.pacman:
    name:
      - docker

- name: Start and enable docker service
  become: true
  become_user: root
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: docker

- name: Add user to docker group
  become: true
  become_user: root
  ansible.builtin.user:
    name: "{{ user.name }}"
    groups: docker
    state: present
    append: true
