---
- name: Install docker
  become: true
  become_user: root
  pacman:
    name:
      - docker

- name: Start and enable docker service
  become: true
  become_user: root
  systemd:
      state: started
      enabled: yes
      name: docker

- name: Add user to docker group
  become: true
  become_user: root
  user:
    name: "{{ user.name }}"
    groups: docker
    state: present
    append: true
