---
- name: Install GPG
  become: true
  become_user: root
  community.general.pacman:
    name:
      - gnupg

- name: Ensure directory exists
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.file:
    path: ~/.gnupg
    state: directory
    mode: 0700

- name: Copy gpg configs
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: ~/.gnupg/
    mode: 0600
  loop:
    - gpg-agent.conf
    - gpg.conf

- name: Set gpg key to use with git
  become: true
  become_user: "{{ user_name }}"
  community.general.git_config:
    name: user.signingkey
    scope: global
    value: "{{ user_gpg_key }}"
  when: user_gpg_key is defined

- name: Set git to always use gpg
  become: true
  become_user: "{{ user_name }}"
  community.general.git_config:
    name: commit.gpgsign
    scope: global
    value: "true"
  when: user_always_git_gpg is defined

- name: Ensure scripts directory exists
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.file:
    path: "~/scripts/gpg"
    state: directory
    mode: 0755

- name: Copy gpg_ scripts
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "~/scripts/gpg"
    mode: 0644
  loop:
    - gpg_setup_keyring.sh


- name: Ensure fish directory exists
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.file:
    path: ~/.config/fish/ansible/gpg
    state: directory
    mode: 0700
  when: fish_install_extensions

- name: Copy fish config
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.copy:
    src: gpg-agent.fish
    dest: ~/.config/fish/ansible/gpg/gpg-agent.fish
    mode: 0644
  when: fish_install_extensions
