---
- name: Install GPG
  become: true
  become_user: root
  community.general.pacman:
    name:
      - gnupg

- name: Ensure directory exists
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.file:
    path: ~/.gnupg
    state: directory
    mode: 0755

- name: Copy gpg config
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.copy:
    src: gpg_config
    dest: ~/.gnupg/gpg-agent.conf
    mode: 0644

- name: Set gpg key to use with git
  become: true
  become_user: "{{ user.name }}"
  community.general.git_config:
    name: user.signingkey
    scope: global
    value: "{{ user.gpg_key }}"
  when: user.gpg_key is defined

- name: Set git to always use gpg
  become: true
  become_user: "{{ user.name }}"
  community.general.git_config:
    name: commit.gpgsign
    scope: global
    value: "true"
  when: user.always_git_gpg is defined
