{% if i3_nvidia_optimus_direct_rendering %}
# Needed for rendering everything on more powerful Nvidia
xrandr --setprovideroutputsource modesetting NVIDIA-0
xrandr --auto
{% endif %}
export SSH_ASKPASS=/usr/lib/ssh/x11-ssh-askpass

xrandr --dpi {{ i3_dpi }}
exec i3
