{% if i3_nvidia_optimus_direct_rendering %}
# Needed for rendering everything on more powerful Nvidia
xrandr --setprovideroutputsource modesetting NVIDIA-0
xrandr --auto
{% endif %}
{% if i3_disable_touchpad %}
# Disable TouchPad
xinput disable $(xinput list | grep -i touchpad | grep -E "id=[0-9]+" -o | cut -d "=" -f2)
{% endif %}
xrandr --dpi {{ i3_dpi }}
autorandr -c || true
exec i3
