---
- name: Core
  hosts: all
  become: true
  become_user: root
  roles:
    - {role: locale, tags: ['locale']}
    - {role: pacman, tags: ['pacman']}
    - {role: pacoloco, tags: ['pacoloco']}
    - {role: ntp, tags: ['ntp']}
    - {role: create_user, tags: ['create_user']}
    - {role: vconsole, tags: ['vconsole']}
    - {role: sudo, tags: ['sudo']}
    - {role: aur_builder, tags: ['aur_builder']}
    - {role: dns_cache, tags: ['dns_cache']}
    - {role: hardening, tags: ['hardening']}
    - {role: openssh, tags: ['openssh']}
    - {role: nftables, tags: ['nftables']}
    # Running this role by default seems fragile, require explicit mention for now
    - {role: mkinitcpio, tags: ['mkinitcpio', 'never']}
    # Same reasoning as for the above
    - {role: refind, tags: ['refind', 'never']}
    - {role: networkmanager, tags: ['networkmanager']}
  tags:
    - core
