---
- name: Mail
  hosts: all
  become: true
  become_user: "{{ user_name }}"
  roles:
    - {role: aerc, tags: ['aerc']}
    - {role: imapnotify, tags: ['imapnotify']}
    - {role: isync, tags: ['isync']}
    - {role: msmtp, tags: ['msmtp']}
    - {role: oama, tags: ['oama'], when: 'email_client | dict2items | selectattr("value.oauth", "defined") | selectattr("value.oauth", "equalto", true) | list | items2dict'}
  tags:
    - mail
    - never

- name: Mail PIM
  hosts: all
  become: true
  become_user: "{{ user_name }}"
  roles:
    - {role: khal, tags: ['khal']}
    - {role: khard, tags: ['khard']}
    - {role: todoman, tags: ['todoman']}
    - {role: vdirsyncer, tags: ['vdirsyncer']}
    - {role: webdav, tags: ['webdav'], when: 'email_client | dict2items | selectattr("value.webdav", "defined") | list | items2dict'}
  tags:
    - mail-pim
    - never
