---
- name: Install some miscellanous stuff.
  become: true
  become_user: root
  community.general.pacman:
    name:
      - sl
      - cmatrix
      - cowsay
      - figlet
      - kernel-modules-hook
      - tree
      - btop
      - zip
