---
- name: Install NetworkManager
  become: true
  become_user: root
  community.general.pacman:
    name: networkmanager
    state: present

- name: Start and enable NM
  become: true
  become_user: root
  ansible.builtin.systemd:
    name: NetworkManager
    enabled: true
    state: started

- name: Install NetworkManager's applet
  become: true
  become_user: root
  community.general.pacman:
    name: network-manager-applet
    state: present
  when: networkmanager_install_gui

- name: Template sway plugin
  ansible.builtin.include_role:
    name: helper_sway_plugin
  vars:
    helper_sway_plugin_template_name: networkmanager-plugin
  when: networkmanager_install_gui
