---
- name: Install NetworkManager
  become: true
  become_user: root
  community.general.pacman:
    name: networkmanager
    state: present

- name: Start and enable NM
  become: true
  become_user: root
  ansible.builtin.systemd:
      name: NetworkManager
      enabled: true
      state: started
