---
- name: Install NetworkManager
  community.general.pacman:
    name: networkmanager
    state: present

- name: Start and enable NM
  ansible.builtin.systemd:
    name: NetworkManager
    enabled: true
    state: started
