---
encryption:
  tag: GRING

redirect_port: 8080

services:
  google:
    client_id: {{oama_google_client_id}}
    client_secret: {{oama_google_client_secret}}
    # Only the first scope is strictly required for email
    # But for the sake of mail-pim let's add all the scopes we might want
    auth_scope: https://mail.google.com/ https://www.googleapis.com/auth/carddav https://www.googleapis.com/auth/calendar
