---
- name: Install mesa
  become: true
  become_user: root
  community.general.pacman:
    name:
      - mesa

- name: Install mesa-demos
  become: true
  become_user: root
  community.general.pacman:
    name:
      - mesa-demos
  when: mesa_install_mesa_demos
