---
- name: Install aerc and pandoc
  become: true
  become_user: root
  community.general.pacman:
    name:
      - aerc
      - pandoc-cli

- name: Ensure directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - ~/.config/aerc
    - ~/.config/aerc/folder-map

- name: Template config files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: ~/.config/aerc
    mode: 0644
  loop:
    - aerc.conf
    - binds.conf

- name: Create folder-map files
  ansible.builtin.copy:
    content: "{{ email_client[key].dir_map | join('\n') }}"
    dest: ~/.config/aerc/folder-map/{{ key }}
    mode: 0644
  loop: "{{ (email_client | dict2items | selectattr('value.dir_map', 'defined') | list | items2dict).keys() }}"
  loop_control:
    loop_var: key

- name: Template accounts file
  ansible.builtin.template:
    src: accounts.conf
    dest: ~/.config/aerc/accounts.conf
    mode: 0600
