---
- name: Install VPN apps
  become: true
  become_user: root
  community.general.pacman:
    name:
      - easy-rsa
      - openvpn

- name: Install networkmanager openvpn addon
  become: true
  become_user: root
  community.general.pacman:
    name:
      - networkmanager-openvpn
  when: openvpn_install_networkmanager_addon
