---
- name: Install fonts
  become: true
  become_user: root
  community.general.pacman:
    name:
      - awesome-terminal-fonts
      - ttf-hack
      - ttf-inconsolata

- name: Install fonts from AUR
  kewlfft.aur.aur:
    name:
      - ttf-font-icons
    state: present
  become: true
  become_user: aur_builder
